CREATE TABLE IF NOT EXISTS detox_users (
	id SERIAL PRIMARY KEY,
	firstname VARCHAR (255) NOT NULL,
	email VARCHAR (255) NOT NULL,
	sent INT NOT NULL,
	password VARCHAR (255) NOT NULL,
	sdate DATETIME NOT NULL
)ENGINE=MyISAM;